print("ingresa 1 tiro")
num1=int(input())
print("ingresa 2 tiros")
num2=int(input())
print("ingresa 3 tiros")
num3=int(input())
print("ingresa 4 tiros")
num4=int(input())
print("ingresa 5 tiros")
num5=int (input())
resultado = num1 + num2 + num3 + num4 + num5
print(resultado)